apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-node-app
spec:
  replicas: 2  
  selector:
    matchLabels:
      app: hello-node-app
  template:
    metadata:
      labels:
        app: hello-node-app
    spec:
      containers:
      - name: hello-node-app
        image: hello-node-image:latest  
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        # ... resources limit
        resources:
            limits:
              cpu: "0.5"  
              memory: 512Mi  
            requests:
              cpu: "0.1"  
              memory: 128Mi
